spring:
  application:
    name: msvc-impresoras
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/cotizadorbbd2
    username: root
    password: Abue2679522

  jpa:
    hibernate:
      ddl-auto: create
      database: mysql
      database-platform: org.hibernate.dialect.MySQL8Dialect